spring:
  application:
    name: config-ser
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yarai930122/test_repo.git
          username: 15821872779@qq.com
          password: 134679
server:
  port: 10088
